version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql_db
    networks:
      - real-estate-agency
    stdin_open: true
  mysql_db:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: real_estate_agency
    ports:
      - '3307:3306'
    networks:
      - real-estate-agency
    volumes:
      - "./src/main/resources/Real_estate_agency.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./src/main/resources/data_initialization_real_estate_agency.sql:/docker-entrypoint-initdb.d/2.sql"
      - "mysql-volume:/var/lib/mysql"

volumes:
  mysql-volume:

networks:
  real-estate-agency:
    name: real-estate-agency
    driver: bridge